const Account = require("./account");

let accounts = [
    new Account("als_31",0),
    new Account("MonkeyCity17",0),
    new Account("jinglesmells1337",0),
    new Account("uuujtagr_81",0),
    new Account("paethetic",0),
    new Account("h6es",0),
    new Account("bighairypasha",0),
    new Account("fev7",0),
    new Account("c_ck",0),
    new Account("cupoflizard",0),
    new Account("mcpoptart",0),
    new Account("shingblad",0),
    new Account("KhanInTheWall",0),
    new Account("norriie",0),
    new Account("minecraftoogle",0),
    new Account("cute_god",0),
    new Account("CRAZYJAKE0617",0),
    new Account("ceebee83",0),
    new Account("jodie237",0),
    new Account("javiles",0),
    new Account("pandapuffz",0),
    new Account("tanman34",0),
    new Account("vibby22",0),
    new Account("xredhound",0),
    new Account("bigboyman96",0),
    new Account("clairemac13",0),
    new Account("kas61",0),
    new Account("merica49",0),
    new Account("yubg",0),
    new Account("itamar080607",0),
    new Account("ilovethe77",0),
    new Account("jqkeup",0),
    new Account("markynoodle",0),
    new Account("blatser",0),
    new Account("matchatw",0),
    new Account("YummosChihuahua",0),
    new Account("botcheetah",0),
    new Account("cakeeplayz",0),
    new Account("heylevy",0),
    new Account("faebled",0),
    new Account("ilomiswir",0),
    new Account("wire21",0),
    new Account("ghostly3",0),
    new Account("fromagepaladin",0),
    new Account("turkeycraft",0),
    new Account("jaywolvian",0),
    new Account("kokosuke",0),
    new Account("jambal",0),
    new Account("kashmoney420",0),
    new Account("n0rr1e_is_b4d",0),
    new Account("codymacke",0),
    new Account("bignick1",0),
    new Account("tigernew",0),
    new Account("bigc1109", 0),
    new Account("sprinngowo",0),
    new Account("verylonelytree",0),
    new Account("pasha300",0),
    new Account("rxob",0),
    new Account("v3n0m__",0),
    new Account("wetasspoggerss",0),
    new Account("bruhpogchamp",0),
    new Account("coolswaggamer",0),
    new Account("eatmyvenom",0),
    new Account("hotcheetah",0),
    new Account("fubyinthecutie",0),
    new Account("fuby",0),
    new Account("mvvi",0),
    new Account("kvdg",0),
    new Account("cobleemil",0),
    new Account("atni",0),
    new Account("kuirie",0),
    new Account("qSpider",0),
    new Account("FionnaBalor",0),
    new Account("_hipo",0),
    new Account("the_devilhimself",0),
    new Account("0name",0),
    new Account("js_juke",0),
    new Account("drgen",0),
    new Account("napness",0),
    new Account("tabananaman",0),
    new Account("badneon",0),
    new Account("daniezowo",0),
    new Account("zhmeva",0),
    new Account("konan1010",0),
    new Account("kyaco",0),
    new Account("haelx",0),
    new Account("mizlynna",0),
    new Account("edwarez",0),
    new Account("llleeee",0),
    new Account("_nadel_",0),
    new Account("Ghostlyboomerang",0),
    new Account("Faevourite",0),
    new Account("verybad_",0),
    new Account("i1a",0),
    new Account("LiamGoneMad",0),
    new Account("steakinthewall",0),
    new Account("WinInTheWall",0),
    new Account("Arcxire",0),
    new Account("USOMUSKY",0),
    new Account("Blackoutburst",0),
    new Account("pastuuh",0),
    new Account("holidee",0),
    new Account("CloverStyle",0),
    new Account("skycity17",0),
    new Account("p3ppa_plg",0),
    new Account("shiins",0),
    new Account("0897david0897",0),
    new Account("lllGhost",0),
    new Account("BLKIN",0),
    new Account("laura_something",0),
    new Account("DarthEsme",0),
    new Account("Ink0taScythe",0),
    new Account("PartyGamesUpdate",0),
    new Account("DrPickle_",0),
    new Account("SuperMinerAAA",0),
    new Account("PokemonCity17",0),
    new Account("Speedblaster",0),
    new Account("Latex_allergy",0),
    new Account("mythicalpingu",0),
    new Account("LunaTheRanger",0),
    new Account("Nebbens",0),
    new Account("Dumboes",0),
    new Account("MiWadiPOG",205),
    new Account("Smertnix",506)
]

let afkers = [
    new Account("Galaxy_Senpai",0),
    new Account("genkai95",0),
    new Account("Chenchen87",0),
    new Account("Swishfox",0),
    new Account("xLightW0lf",0),
    new Account("Riiruu",0),
    new Account("Cale73",0),
    new Account("Aplanna",0),
    new Account("Gigchad",0),
    new Account("Sebastitgames",0),
    new Account("Musgravite", 0),
    new Account("jkGALAKTUS",0),
    new Account("Pe3tr",0),
    new Account("knacam",0),
    new Account("Cukrenka",0),
    new Account("FortuneLemon",0),
    new Account("Aldix",0),
    new Account("Krumpachnik",0),
    new Account("aByee",0),
    new Account("ZenBenn",0),
    new Account("ThePoGoCZ",0),
    new Account("MasonInTheWall",0),
    new Account("bunniexoxo",0),
    new Account("HammyInTheWall",0),
    new Account("UekuInTheWall",0),
    new Account("xHugTacos",25),
    new Account("LoverBoyCanadian", 0),
    new Account("canadiansweat", 0),
    new Account("Oblueish",28),
    new Account("TomerWB",104),
    new Account("Osunburst",12),
    new Account("Cuseno",147),
    new Account("Falsehacker",58),
    new Account("InfamousJUK3D",0),
    new Account("Hiejo",35),
    new Account("oMarc",28),
    new Account("Frightt",59),
    new Account("Pallah",0),
    new Account("DutchMark",0),
    new Account("Rowdies",53),
    new Account("SilverPat",19),
    new Account("strqnded",78),
    new Account("xArctic",55),
    new Account("ilovealice2000",49),
    new Account("kigz",38),
    new Account("Intensefy",59),
    new Account("GloriousYellow",0),
    new Account("swaggerdawg69",104),
    new Account("Cubxr",62),
    new Account("Almighty_Dab",0),
    new Account("SirFuzzyMonkey",0),
    new Account("NoHackzJustAsian",0),
    new Account("UnitxdStates",45),
    new Account("Chilled_Thunder",21),
    new Account("Bqsketball",7),
    new Account("riskytaunt",0),
    new Account("xmuffins",1)
];

let important = [
    new Account("plancke",0),
    new Account("AgentKid",0),
    new Account("hypixel",0),
    new Account("SlothPixel",0),
    new Account("Plancker",0),
    new Account("Plank",0),
    new Account("SenorPancake",0),
    new Account("ZeroErrors",0),
    new Account("MasterControl",0),
    new Account("Thorlon",0),
    new Account("Sylent_",0),
    new Account("SylentButDedly",0),
    new Account("LadyBleu",0),
]

let yt = [
    new Account("Technoblade",0),
    new Account("Dream",0),
    new Account("elybeatmaker",0),
    new Account("gamerboy80",0),
    new Account("Illumina",0),
    new Account("Purpled",0),
    new Account("TapL",0),
    new Account("Zyphon_",0),
]

let pog = [
    new Account("pr0cess"),
    new Account("smokey95dog"),
    new Account("Rechenmaschine")
]

module.exports = {accounts: accounts.concat(afkers, important ,yt, pog),gamers:accounts, afkers : afkers, important: important, yt:yt, pog:pog} 