module.exports = {
  apps: [
    {
      name: "API",
      script: "yarn api",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: true,
    },
    {
      name: "Site",
      script: "yarn site",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: true,
    },
    {
      name: "Bot",
      script: "yarn bot",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: true,
    },
    {
      name: "MIWBot",
      script: "yarn bot mw",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: true,
    },
    {
      name: "Worker",
      script: "yarn worker",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: true,
    },
    {
      name: "Cache",
      script: "yarn refreshcache",
      error_file: "/dev/null",
      out_file: "/dev/null",
      combine_logs: true,
      restart: false,
      autorestart: false,
      cron_restart: "*/20 * * * *",
    },
  ],
};
