
module.exports = function plrs(accs) {
    let accounts=accs
    let Player = require('./player')(accounts);
    return [
        new Player("Als", ["als_31"]),
        new Player("Monkey", ["monkeycity17","jinglesmells1337"]),
        new Player("Ugy", ["uuujtagr_81"]),
        new Player("Pae", ["paethetic","h6es","bighairypasha","fev7","c_ck","cupoflizard"]),
        new Player("Poptart", ["mcpoptart"]),
        new Player("Shing", ["shingblad"]),
        new Player("Khan", ["KhanInTheWall"]),
        new Player("Norrie", ["norriie"]),
        new Player("Oogle", ["minecraftoogle","cute_god","CRAZYJAKE0617","ceebee83","jodie237","javiles","pandapuffz","tanman34","vibby22","xredhound","bigboyman96","clairemac13","kas61","merica49"]),
        new Player("Yung", ["yubg"]),
        new Player("Itamar", ["itamar080607"]),
        new Player("THE77", ["ilovethe77"]),
        new Player("Jake", ["jqkeup","Faevourite"]),
        new Player("Marky", ["Markynoodle"]),
        new Player("Blatser", ["blatser"]),
        new Player("Matcha", ["Matchatw"]),
        new Player("Cryo", ["YummosChihuahua"]),
        new Player("Cheetah", ["botcheetah"]),
        new Player("Cakee", ["cakeeplayz"]),
        new Player("Levy", ["HeyLevy"]),
        new Player("Fae", ["faebled"]),
        new Player("Ilomiswir", ["Ilomiswir"]),
        new Player("Wire", ["wire21"]),
        new Player("Ghostly", ["ghostly3","ghostlyboomerang","fromagepaladin","turkeycraft","jaywolvian","kokosuke","jambal","kashmoney420","n0rr1e_is_b4d","codymacke","bignick1","tigernew"]),
        new Player("BigC", ["Bigc1109","sprinngowo"]),
        new Player("Tree",["verylonelytree"]),
        new Player("pasha", ["pasha300"]),
        new Player("Rxob", ["Rxob"]),
        new Player("venom", ["v3n0m__","bruhpogchamp","wetasspoggerss","coolswaggamer","hotcheetah","eatmyvenom"]),
        new Player("Fuby", ["fubyinthecutie","Fuby"]),
        new Player("Mavis", ["mvvi"]),
        new Player("Kev", ["kvdg"]),
        new Player("Cob", ["Cobleemil"]),
        new Player("Anti", ["Atni"]),
        new Player("Kuiri", ["Kuirie"]),
        new Player("Spider", ["qSpider"]),
        new Player("Fionna", ["FionnaBalor"]),
        new Player("Hipo", ["_Hipo"]),
        new Player("Devil", ["The_DevilHimself"]),
        new Player("0name", ["0name"]),
        new Player("Juke", ["js_juke"]),
        new Player("drgen", ["drgen"]),
        new Player("Nap", ["napness"]),
        new Player("Tab", ["Tabananaman"]),
        new Player("Neon", ["badneon"]),
        new Player("Daniez", ["Daniezowo"]),
        new Player("Zhmeva", ["zhmeva"]),
        new Player("Konan", ["Konan1010"]),
        new Player("Kyaco", ["Kyaco"]),
        new Player("Haelx", ["Haelx"]),
        new Player("Mizlynna", ["mizlynna"]),
        new Player("Edwarez", ["edwarez"]),
        new Player("Llleeee", ["llleeee"]),
        new Player("Nadel", ["_nadel_"]),
        new Player("Pingu", ["mythicalpingu"]),
        new Player("dee" , ["holidee"])
    ];
}