module.exports = {
  zombies: {
    fastest_time_10_zombies_alienarcadium_normal: true,
    fastest_time_10_zombies: true,
    fastest_time_20_zombies_alienarcadium_normal: true,
    fastest_time_20_zombies: true,
    fastest_time_10_zombies_badblood_normal: true,
    fastest_time_20_zombies_badblood_normal: true,
    fastest_time_10_zombies_deadend_normal: true,
    fastest_time_20_zombies_deadend_normal: true,
    fastest_time_30_zombies: true,
    fastest_time_30_zombies_deadend_normal: true,
    fastest_time_30_zombies_badblood_normal: true,
    fastest_time_10_zombies_badblood_hard: true,
    fastest_time_20_zombies_badblood_hard: true,
    fastest_time_30_zombies_badblood_hard: true,
    fastest_time_10_zombies_badblood_rip: true,
    fastest_time_20_zombies_badblood_rip: true,
    fastest_time_10_zombies_deadend_hard: true,
    fastest_time_20_zombies_deadend_hard: true,
    fastest_time_30_zombies_badblood_rip: true,
    fastest_time_10_zombies_deadend_rip: true,
    fastest_time_20_zombies_deadend_rip: true,
    fastest_time_30_zombies_deadend_rip: true,
    fastest_time_30_zombies_deadend_hard: true,
    fastest_time_30_zombies_alienarcadium_normal: true,
  },
};
